<?php
$questionlist = array('Podaj swoje imię i nazwisko?',
'Jak masz na drugie imię?',
'Twoja ksywka.',
'Ile masz lat?',
'Jaki masz kolor oczu?',
'Jaki masz kolor włosów?',
'Czy masz jakieś znaki szczególe (jakie)?',
'W której jesteś klasie?',
'Masz przyjaciółkę/ przyjaciela?',
'Jak ma na imię Twoja przyjaciółka/przyjaciel?',
'Kogo najbardziej lubisz w swojej klasie?',
'Jaki jest twój znak zodiaku?',
'Masz sympatię?',
'Jak ma na imię Twoja sympatia?',
'Kiedy się urodziłaś/urodziłeś?',
'Kiedy masz imieniny?',
'Masz rodzeństwo?',
'Jak się nazywa Twoje rodzeństwo?',
'Ile ma/mają lat?',
'Co lubisz robić?',
'Czego nie lubisz robić?',
'Twoja ulubiona potrawa?',
'Czego najbardziej nie lubisz jeść?',
'Jaka jest twoja ulubiona słodycz?',
'Jaki smak najbardziej lubisz (słodki, słony, kwaśny i gorzki)?',
'Jakiego smaku najbardziej nie lubisz (słodki, słony, kwaśny i gorzki)?',
'Jakie lubisz zwierzęta?',
'Masz zwierzę?',
'Jakie imię żeńskie ci się najbardziej podoba?',
'Jakie imię męskie ci się najbardziej podoba?',
'Jakiego aktora polskiego najbardziej lubisz?',
'Jaką aktorkę polską najbardziej lubisz?',
'Jakiego aktora zagranicznego najbardziej lubisz?',
'Jaką aktorkę zagraniczną najbardziej lubisz?',
'Jakiego piosenkarza polskiego najbardziej lubisz?',
'Jakiego piosenkarza zagranicznego najbardziej lubisz?',
'Jaką piosenkarkę polską najbardziej lubisz?',
'Jaką piosenkarkę zagraniczną najbardziej lubisz?',
'Jaki zespół polski najbardziej lubisz?',
'Jaki zespół zagraniczny najbardziej lubisz?',
'Jaki jest twój ulubiony film?',
'Jaki jest twój ulubiony serial?',
'Czy lubisz śpiewać?',
'Czy grasz na jakimś instrumencie (na jakim)?',
'Czy lubisz tańczyć?',
'Czy lubisz rysować/malować?',
'Jaki jest twój dyscyplina sportowa?',
'Jaki jest Twój ulubiony sportowiec?',
'Uprawiasz jakiś sport (jaki)?',
'Czy grasz w gry komputerowe?',
'Jaka jest twoje ulubiona gra komputerowa?',
'Czy grasz w gry planszowe?',
'Jaka jest twoja ulubiona gra planszowa?',
'Czego nigdy byś nie zrobił/zrobiła?',
'O czym marzysz?',
'Wybrałbyś/wybrałabyś lot w kosmos czy zwiedzanie podwodnych światów?',
'Czy marzyłeś/marzyłaś o lataniu (jak ptak)?',
'Jakim zwierzęciem chciałbyś/chciałabyś być?',
'Jaką rośliną chciałabyś/chciałabyś być?',
'Czy marzysz o podróży dookoła świata?',
'Co byś zrobił/zrobiła gdybyś wygrał/wygrała dużo pieniędzy?',
'Co byś zmienił/zmieniła na świecie?',
'Byłeś/byłaś kiedyś na koloni lub obozie?',
'Jakiego obcego języka się uczysz?',
'Gdzie chciałbyś/chciałabyś pojechać na wakacje?',
'Wolisz góry czy morze?',
'Co według Ciebie jest nudne?',
'Co Ci się wydaje w życiu najtrudniejsze?',
'Co Cię smuci?',
'Czego się boisz?',
'Co Cię drażni u innych osób?',
'Jakiej cechy nie lubisz u siebie?',
'Jakie masz zalety?',
'Jakie cechy charakteru cenisz u innych?',
'Jak radzisz sobie ze stresem?',
'Jesteś osobą otwartą czy raczej skrytą?',
'Łatwo ci rozmawiać o sowich uczuciach?',
'Komu się zwierzasz?',
'Czy jest ktoś komu możesz bezwzględnie ufać?',
'Czy ktoś kiedyś zawiódł twoje zaufanie?',
'Czy uważasz, że zawsze należy mówić prawdę?',
'Czy śnią ci się czasem koszmary?',
'Czy łatwo wpadasz w gniew?',
'Czy łatwo się wzruszasz?',
'Czy jesteś przesądny/przesądna?',
'Czy wierzysz w duchy?',
'Czy wierzysz w UFO i istoty pozaziemskie?',
'Co zabrałbyś na bezludną wyspę (3 rzeczy)?',
'Czy byłeś/byłaś gdzieś za granicą (gdzie)?',
'Podaj ulubioną markę samochodu.',
'Czy lubisz chodzić do kina?',
'Czy lubisz chodzić do teatru?',
'Czy lubisz chodzić do muzeów?',
'Czy lubisz chodzić do galerii sztuki?',
'Czy lubisz czytać książki?',
'Jaka książka jest twoją ulubioną?',
'Kim chciałbyś/chciałabyś zostać w przyszłości?',
'Jakie masz hobby?',
'Wymień trzy rzeczy, których utrata byłaby dla ciebie bardzo bolesna.',
'Jaki jest twój ulubiony dzień tygodnia?',
'Jakiego dnia tygodnia najbardziej nie lubisz?',
'Jaką porę roku najbardziej lubisz?',
'Jakiej pory roku najbardziej nie lubisz?',
'Jaką porę dnia najbardziej lubisz?',
'Jakiej pory dnia najbardziej nie lubisz?',
'Jesteś „nocnym markiem” czy „chodzisz spać z kurami”?',
'Jaki jest twój ulubiony miesiąc?',
'Jakiego miesiąca najbardziej nie lubisz?',
'Jaka jest twoja ulubiona liczna?',
'Jakiej liczby najbardziej nie lubisz?',
'Jaki najbardziej przedmiot lubisz w szkole?',
'Jakiego przedmiotu najbardziej nie lubisz?',
'Podaj e-mail.',
'Podaj NIK na skypea.',
'Czy odpowiedziałeś/odpowiedziałaś szczerze na wszystkie pytania?'

);
